services:
  sftp:
    build:
      context: .
      dockerfile: Containerfile
    image: diquzart/sftp:v1.0.0-ubi
    container_name: sftp-ubi
    ports:
      - "2222:22"
    environment:
      SFTP_USER: user1
      SFTP_KEY_PATH: /config/authorized_keys
    volumes:
      - ~/.ssh/id_ed25519.pub:/config/authorized_keys:ro
      - ./download:/sftp/user1/download
      - ./sshd_config:/etc/ssh/sshd_config:ro
    entrypoint: ["/entrypoint.sh"]
    restart: unless-stopped
