FROM debian:bookworm-slim

LABEL maintainer="Muhammed Iqbal <iquzart@hotmail.com>"
LABEL description="Hardened Debian SFTP server with CIS SSH compliance"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
  apt-get install -y --no-install-recommends openssh-server && \
  rm -rf /var/lib/apt/lists/* && \
  mkdir -p /var/run/sshd /sftp && \
  chmod 755 /sftp

COPY sshd_config /etc/ssh/sshd_config

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 22

ENTRYPOINT ["/entrypoint.sh"]

